version: '3.7'

networks:
    puttxt:
        driver: bridge
volumes:
    app-data:

services:

    nginx:
        image: nginx:1.17-alpine
        container_name: puttxt-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./project:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - puttxt
    
    app:
        build:
            args:
                user: kylepantall
                uid: 1000
            context: ./docker/php
            dockerfile: Dockerfile
        image: puttxt
        container_name: puttxt-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./project:/var/www
        networks:
            - puttxt

    db:
        image: mysql:5.7
        container_name: puttxt-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: putTxt
            MYSQL_ROOT_PASSWORD: putTxtRoot
            MYSQL_PASSWORD: putTxtPassword
            MYSQL_USER: putTxtUser
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - app-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - puttxt

    mailhog:
        image: mailhog/mailhog
        container_name: puttxt_mail
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - puttxt

    node:
        build:
            args:
                user: root
                uid: 1000
            context: ./docker/node
            dockerfile: Dockerfile
        container_name: puttxt-npm
        volumes:
            - ./project:/usr/src/
        networks:
            - puttxt